module 22.5/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/', views.UserBankAccountUpdateView.as_view(), name='profile'),
]

module 22.5/amar_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

module 22.5/transactions/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('deposit/', views.DepositMoneyView.as_view(), name='deposit_money'),
    path('withdraw/', views.WithdrawMoneyView.as_view(), name='withdraw_money'),
    path('report/', views.TransactionReportView.as_view(), name='transaction_report'),
    path('loan_request/', views.LoanRequestView.as_view(), name='loan_request'),
    path('loans/', views.LoanListView.as_view(), name='loan_list'),
    path('loans/<int:loan_id>/', views.PayLoanView.as_view(), name='pay'),
    path('transfer/', views.TransferView.as_view(), name='transfer'),
]

module 22.5/transactions/models.py
from django.db import models
from accounts.models import UserBankAccount
from .constants import TRANSACTION_TYPE

# Create your models here.

class Transaction(models.Model):
    account = models.ForeignKey(UserBankAccount, related_name='transaction', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    balance_after_transaction = models.DecimalField(max_digits=12, decimal_places=2)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE)
    timestamp = models.DateTimeField(auto_now_add=True)
    loan_approve = models.BooleanField(default=False)

    class Meta:
        ordering = ['timestamp']
        

module 22.5/transactions/forms.py
from typing import Any
from django import forms
from .models import Transaction


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'transaction_type']

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)
        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()
    

class DepositForm(TransactionForm):
    def clean_amount(self):
        min_deposit_amount= 100
        amount = self.cleaned_data.get('amount')
        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f'You need to deposit at least TK. {min_deposit_amount}'
            )
        return amount


class WithdrawForm(TransactionForm):
    def clean_amount(self):
        account = self.account
        min_withdraw_amount = 500
        max_withdraw_amount = 2000000
        balance = account.balance
        amount = self.cleaned_data.get('amount')
        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at least TK. {min_withdraw_amount}'
            )
        
        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw maximum Tk. {max_withdraw_amount} at a time'
            )
        
        if amount > balance :
            raise forms.ValidationError(
                f'You have TK. {balance} in your account. '
                'You can not withdraw more then your account balance'
            )
        return amount
    


class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')

        return amount
    
class TransferAnotherAcc(TransactionForm):
    receiver_account = forms.CharField(required=True)
    class Meta:
        model = Transaction
        fields = ['amount', 'receiver_account', 'transaction_type']


    def clean_amount(self):
        amount = self.cleaned_data.get("amount")
        min_transfer_amount = 100
        if amount < min_transfer_amount :
            raise forms.ValidationError(f'The minimum transfer amount is TK. {min_transfer_amount}')
        
        return amount
    
    

module 22.5/transactions/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic import CreateView, ListView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Transaction
from .forms import DepositForm, WithdrawForm, LoanRequestForm, TransferAnotherAcc
from .constants import *
from django.contrib import messages
from datetime import datetime
from django.db.models import Sum
from django.urls import reverse_lazy
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.contrib.auth.models import User

# Create your views here.

def send_transaction_email(user, amount, subject, template):
    message = render_to_string(template, {
        'user' : user,
        'amount' : amount
    })
    send_email = EmailMultiAlternatives(subject, '', to=[user.email])
    send_email.attach_alternative(message, 'text/html')
    send_email.send()

class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'transactions/transaction_form.html'
    model = Transaction
    title = ''
    success_url = reverse_lazy('transaction_report')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account' : self.request.user.account,
        })
        return kwargs
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context.update({
            'title': self.title
        })
        return context


class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposit'

    def get_initial(self):
        initial = {'transaction_type': DEPOSIT}
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance += amount
        account.save(
            update_fields = ['balance']
        )

        messages.success(self.request, f'TK. {amount} deposited to your account successfully')
        # mail_subject = 'Deposite message'
        # message = render_to_string('transactions/deposite_mail.html', {
        #     'user' : self.request.user,
        #     'amount' : amount
        # })
        # to_email = self.request.user.email
        # send_email = EmailMultiAlternatives(mail_subject, '', to=[to_email])
        # send_email.attach_alternative(message, 'text/html')
        # send_email.send()
        send_transaction_email(self.request.user, amount, 'Deposite Message', 'transactions/deposite_mail.html')
        return super().form_valid(form)
    

class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw'

    def get_initial(self):
        initial = {'transaction_type': WITHDRAWAL}
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance -= amount
        account.save(
            update_fields = ['balance']
        )

        messages.success(self.request, f'TK. {amount} Withdraw from your account successfully')
        send_transaction_email(self.request.user, amount, 'withdrawal Message', 'transactions/withdraw_email.html')
        return super().form_valid(form)
    

class LoanRequestView(TransactionCreateMixin):
    form_class = LoanRequestForm
    title = 'Request for Loan'

    def get_initial(self):
        initial = {'transaction_type': LOAN}
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        current_loan_count = Transaction.objects.filter(account=self.request.user.account, transaction_type = LOAN, loan_approve = True).count()

        if current_loan_count >= 3:
            return HttpResponse("You cross the loan limits")
        
        messages.success(self.request, f'Loan Request for amount TK.{amount} has been successfully sent to Bank.')
        send_transaction_email(self.request.user, amount, 'Loan Request Message', 'transactions/loan_request_email.html')
        return super().form_valid(form)



class TransactionReportView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_report.html'
    model = Transaction
    balance = 0

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            account = self.request.user.account
        )

        start_date_str = self.request.GET.get('start_date')
        end_date_str = self.request.GET.get('end_date')

        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, "%Y-%m-%d").date()
            end_date = datetime.strptime(end_date_str, "%Y-%m-%d").date()

            queryset = queryset.filter(timestamp__date__gte = start_date, timestamp__date__lte = end_date)
            self.balance = Transaction.objects.filter(
                timestamp__date__gte=start_date, timestamp__date__lte=end_date
            ).aggregate(Sum('amount'))['amount__sum']

        else:
            self.balance = self.request.user.account.balance

        return queryset.distinct()
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account': self.request.user.account
        })
        return context
    


class PayLoanView(TransactionCreateMixin, View):
    def get(self, request, loan_id):
        loan = get_object_or_404(Transaction, id = loan_id)

        if loan.loan_approve:
            user_account = loan.account
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.transaction_type = LOAN_PAID
                loan.save()
                send_transaction_email(self.request.user, '1000', 'Loan Paid Message', 'transactions/loan_paid_email.html')
                return redirect('loan_list')
            else:
                messages.error(self.request, f'Loan amount is grater than available balance')
                return redirect('loan_list')



class LoanListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'transactions/loan_request.html'
    context_object_name = 'loans'


    def get_queryset(self):
        user_account = self.request.user.account
        queryset = Transaction.objects.filter(account = user_account, transaction_type=LOAN)
        return queryset



class TransferView(TransactionCreateMixin):
    form_class = TransferAnotherAcc
    title = 'Transfer Money'

    def get_initial(self):
        initial = {'transaction_type': TRANSFER}
        return initial
    
    def form_valid(self, form):
        sender_account = self.request.user.account
        receiver_account_name = form.cleaned_data.get('receiver_account')
        print("ereceiver_account_name")
        receiver_amount = form.cleaned_data.get('amount')

        try:
            receiver_user = User.objects.get(username=receiver_account_name)
        except User.DoesNotExist:
            messages.error(self.request, "Receiver account not found.")
            return super().form_invalid(form)

        if sender_account.balance < receiver_amount:
            messages.error(self.request, "Insufficient balance for the transfer.")
            return super().form_invalid(form)

        sender_account.balance -= receiver_amount
        sender_account.save(
            update_fields = ['balance']
        )

        receiver_account = receiver_user.account
        receiver_account.balance += receiver_amount
        receiver_account.save(
            update_fields = ['balance']
        )


        messages.success(self.request, f'Transferred TK. {receiver_amount} to {receiver_account} successfully')
        send_transaction_email(self.request.user, receiver_amount, 'Transfer Message', 'transactions/transfer_email.html')
        return super().form_valid(form)



        
        
    
        




    

module 22.5/transactions/templates/transactions/admin_email.html
<p>Hello {{user.first_name}} {{user.last_name}}, </p>
<br>
<h2>Congratulation! Your Loan request has been approved....</h2>
<p>Your Loan request for BDT {{amount}} has been successfully Approved. After approv your loan Request your current balance is {{user.account.balance}}. </p>
<br>
<p>Please Pay your loan on time. Otherwise will add extra extra charge or take any kind of legal action</p>
<br>
<p>Thank you for Banking with us</p>
<p>Vctory Bank</p>

module 22.5/transactions/templates/transactions/deposite_mail.html
<p>Hello {{user.first_name}} {{user.last_name}}, </p>
<br>

<p>Your Deposite request for BDT {{amount}} has been successfully deposited. After deposite your total amount is BDT {{user.account.balance}}</p>
<br>

<p>Thank you for Banking with us</p>
<p>Vctory Bank</p>

module 22.5/transactions/templates/transactions/loan_paid_email.html
<p>Hello {{user.first_name}} {{user.last_name}}, </p>
<br>
<h2>Thanks! for Paying loan on time</h2>
<p>You pay your loan on time. After pay your loan your current balance is {{user.account.balance}}. </p>
<br>
<p>Thank you for Banking with us</p>
<p>Vctory Bank</p>

module 22.5/transactions/templates/transactions/loan_request.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 
{% block body %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Loan Report</h1>
  <hr />
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">LOAN ID</th>
        <th class="px-4 py-2">Loan Amount</th>
        <th class="px-4 py-2">Loan Approved</th>
        <th class="px-4 py-2">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for loan in loans %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
         {{ loan.id }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm text-green-700 bg-green-100"
          >
            {{ loan.amount }}
          </span>
        </td>
        <td class="px-4 py-2">
          {{ loan.loan_approve }}
        </td>
        <td class="px-4 py-2">
          {% if loan.loan_approve %}
          <a class="font-bold bg-red-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" href='{% url "pay" loan.id %}'>Pay</a>
          {% else %}
          <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

module 22.5/transactions/templates/transactions/loan_request_email.html
<p>Hello {{user.first_name}} {{user.last_name}}, </p>
<br>

<p>Your Loan request for BDT {{amount}} has been successfully send to Bank. Wait for Bank approval. After getting Bank approval you will get loan and also an email.</p>
<br>

<p>Thank you for Banking with us</p>
<p>Vctory Bank</p>

module 22.5/transactions/templates/transactions/transaction_form.html
{% extends 'base.html' %} {% block head_title %}
  {{ title }}
{% endblock %}
 {% block body %}
  <div class="w-full flex mt-5 justify-center">
    <div class="bg-white w-5/12 rounded-lg">
        {% if title == 'Request for Loan' %}
            <div>
            <a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{% url 'loan_list' %}">View All Loan List</a>
            </div>
        {% endif %}

      <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
      <form method="post" class="px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
          <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">Amount</label>
          <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount" />
        </div>
        {% if title == "Transfer Money" %}
        <div class="mb-4">
          <label class="block text-gray-700 text-sm font-bold mb-2" for="account">Acc No</label>
          <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="receiver_account" id="account" type="text" required placeholder="Account no" />
        </div>
        {% endif %}
        {% if form.amount.errors %}
          {% for error in form.amount.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
          {% endfor %}
        {% endif %}
        <div class="flex w-full justify-center">
          <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">Submit</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

module 22.5/transactions/templates/transactions/transaction_report.html
{% extends 'base.html' %} 
{% load static %}
{% load humanize %}
{% block head_title %} Transaction Report{% endblock %} {% block body %}


<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'transaction_report' %}">
    <div class="flex justify-center">
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2"
      >
        <label for="start_date">From:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="start_date"
          name="start_date"
        />
      </div>
 
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12"
      >
        <label for="end_date">To:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="end_date"
          name="end_date"
        />
      </div>
      <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
        <button
          class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          type="submit"
        >
          Filter
        </button>
      </div>
    </div>
  </form>
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in object_list %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-red-700 bg-red-100 {% else %} text-green-700 bg-green-100 {% endif %}"
          >
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.amount|floatformat:2|intcomma }}
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}
        </td>
      </tr>
      {% endfor %}
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
        <th class="px-4 py-2 text-left">
          $ {{ account.balance|floatformat:2|intcomma }}
        </th>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

module 22.5/transactions/templates/transactions/transfer_email.html
<p>Hello {{user.first_name}} {{user.last_name}}, </p>
<br>

<p>Your Transfer request for BDT {{receiver_amount}} has been successfully Transfer. After Transfer your total amount is BDT {{user.account.balance}}</p>
<br>

<p>Thank you for Banking with us</p>
<p>Vctory Bank</p>

module 22.5/transactions/templates/transactions/withdraw_email.html
<p>Hello {{user.first_name}} {{user.last_name}}, </p>
<br>

<p>Your withdraw request for BDT {{amount}} has been successfully withdraw. After withdrawal your total amount is BDT {{user.account.balance}}</p>
<br>

<p>Thank you for Banking with us</p>
<p>Vctory Bank</p>